name: AI_music_Key_Finder
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^8.0.0+1
  flutter_sound: ^9.2.13
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  http: ^1.2.1
  flutter_voice_recorder: ^0.0.2
  social_media_recorder: ^1.1.13


  path: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter_launcher_icons: ^0.9.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/images.jpeg
  
  